language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t houyunting/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true houyunting/react-test npm run test

after_success:
  - docker build -t houyunting/multi-client ./client
  - docker build -t houyunting/multi-nginx ./nginx
  - docker build -t houyunting/multi-server ./server
  - docker build -t houyunting/multi-worker ./worker

  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # Take those images and push them to docker hub
  - docker push houyunting/multi-client
  - docker push houyunting/multi-nginx
  - docker push houyunting/multi-server
  - docker push houyunting/multi-worker
# deploy:
#     edge: true
#     provider: elasticbeanstalk
#     region: "us-west-1"
#     app: "multi-docker-new"
#     env: "MultiDockerNew-env"
#     bucket_name: "elasticbeanstalk-us-west-1-840367840723"
#     bucket_path: "multi-docker"
#     on:
#         branch: master
#     access_key_id: $AWS_ACCESS_KEY
#     secret_access_key: $AWS_SECRET_KEY
